In [1]:
%run "E:\Users\puzheng\Documents\Startup_py3.py"
sys.path.append(r"E:\Users\puzheng\Documents")

import ImageAnalysis3 as ia
%matplotlib notebook
# import imageAnalysis3 related
from ImageAnalysis3 import library_tools
from ImageAnalysis3.library_tools import _readout_folder
from ImageAnalysis3.library_tools import readouts
# sequence related
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.Alphabet import IUPAC
from Bio.SeqRecord import SeqRecord

In [2]:
readout_folder = r'\\10.245.74.212\Chromatin_NAS_2\Libraries\Readouts'
merfish_readout_folder = os.path.join(readout_folder, "MERFISH_readouts")

In [17]:
# load existing merfish readouts
import pandas as pd

xls = pd.ExcelFile(os.path.join(merfish_readout_folder, 'readout_table_v2.xls'))
readout_table = xls.parse()
xls.close()

In [18]:
# load existing amplifiers
amplifier_folder = r'\\10.245.74.212\Chromatin_NAS_2\Libraries\Amplifiers'
import pandas as pd

xls = pd.ExcelFile(os.path.join(amplifier_folder, 'chenglong_amplifiers.xlsx'))
amplifier_table = xls.parse()
xls.close()
print(amplifier_table)

    Bit Original readout sequences  \
0     1      ATCCTCCTTCAATACATCCC    
1     2       ACACTACCACCATTTCCTAT   
2     3       ACTCCACTACTACTCACTCT   
3     4       ACCCTCTAACTTCCATCACA   
4     5       ACCACAACCCATTCCTTTCA   
5     6       TTTCTACCACTAATCAACCC   
6     7       ACCCTTTACAAACACACCCT   
7     8       TCCTATTCTCAACCTAACCT   
8     9       TATCCTTCAATCCCTCCACA   
9    10       ACATTACACCTCATTCTCCC   
10   11       TTTACTCCCTACACCTCCAA   
11   12       TTCTCCCTCTATCAACTCTA   
12   13       ACCCTTACTACTACATCATC   
13   14       TCCTAACAACCAACTACTCC   
14   15       TCTATCATTACCCTCCTCCT   
15   16       TATTCACCTTACAAACCCTC   

                         Primary amplifier sequences   \
0   ACACTTTCACCTTCCCATTA TT ACACTTTCACCTTCCCATTA T...   
1   TCCCAACACATCCTATCTCA TA TCCCAACACATCCTATCTCA T...   
2   ACCCATTACTCCATTACCAT AT ACCCATTACTCCATTACCAT A...   
3   TATCATCCTTACACCTCACT AA TATCATCCTTACACCTCACT A...   
4   ACTCTCCTTTCCCATAACCT AT ACTCTCCTTTCCCATAACCT A...   
5   ATCATCA

In [19]:
amplifier_table.columns

Index(['Bit', 'Original readout sequences', 'Primary amplifier sequences ',
       'Secondary amplifier sequences', ' Final readout sequences'],
      dtype='object')

In [27]:
Seq(amplifier_table['Primary amplifier sequences '][1].replace(' ',''))

Seq('TCCCAACACATCCTATCTCATATCCCAACACATCCTATCTCATATCCCAACACA...TAT')

(array(['ACACTACCACCATTTCCTAT', 'TA', 'TCCCAACACATCCTATCTCA'], dtype='<U20'),
 array([1, 5, 5], dtype=int64))

In [34]:
# load readout sites
adaptor_folder = r'\\10.245.74.212\Chromatin_NAS_2\Libraries\Adaptors'
readout_site_file = os.path.join(adaptor_folder, 'Readout_sites.fasta')
readout_sites = []
with open(readout_site_file, 'r') as _rd_handle:
    for _readout in SeqIO.parse(_rd_handle, "fasta"):
        readout_sites.append(_readout)
print(readout_sites)

[SeqRecord(seq=Seq('TTTGCACTGCCGTCCTTGAC', SingleLetterAlphabet()), id='Stv_82', name='Stv_82', description='Stv_82 cy7 rev-com_last20', dbxrefs=[]), SeqRecord(seq=Seq('GATCCGATTGGAACCGTCCC', SingleLetterAlphabet()), id='Stv_1', name='Stv_1', description='Stv_1 cy5 rev-com_last20', dbxrefs=[]), SeqRecord(seq=Seq('TGCGAACTGTCCGGCTTTCA', SingleLetterAlphabet()), id='Stv_79', name='Stv_79', description='Stv_79 cy3 rev-com_last20', dbxrefs=[])]


'GGGACGGTTCCAATCGGATC'

In [63]:
_new_seq_str.replace("C",'c')

'ATcATcAAcAccTcATcAAc AT ATcATcAAcAccTcATcAAc AT ATcATcAAcAccTcATcAAc AT ATcATcAAcAccTcATcAAc AT ATcATcAAcAccTcATcAAc AT TTTcTAccAcTAATcAAccc'

In [81]:
amplifier_table.keys()

Index(['Bit', 'Original readout sequences', 'Primary amplifier sequences ',
       'Secondary amplifier sequences', ' Final readout sequences'],
      dtype='object')

In [103]:
new_primary_amplifiers = []
# regenerate new amplifier
for _i in range(6):
    _seq_str = amplifier_table['Primary amplifier sequences '][_i]
    _seqs, _cts = np.unique(_seq_str.split(' '), return_counts=True)
    print(str(_seqs[np.where(_cts==1)[0]][0]), str(readout_sites[_i%3].reverse_complement().seq) )
    _new_seq_str = str(_seq_str).replace(str(_seqs[np.where(_cts==1)[0]][0]), 
                         str(readout_sites[_i%3].reverse_complement().seq) ).replace(' ','')
    
    _new_seq = SeqRecord(Seq(_new_seq_str), id=f"{readout_sites[_i%3].id}_bit{amplifier_table['Bit'][_i]}_primary", description='')
    new_primary_amplifiers.append(_new_seq)

ATCCTCCTTCAATACATCCC GTCAAGGACGGCAGTGCAAA
ACACTACCACCATTTCCTAT GGGACGGTTCCAATCGGATC
ACTCCACTACTACTCACTCT TGAAAGCCGGACAGTTCGCA
ACCCTCTAACTTCCATCACA GTCAAGGACGGCAGTGCAAA
ACCACAACCCATTCCTTTCA GGGACGGTTCCAATCGGATC
TTTCTACCACTAATCAACCC TGAAAGCCGGACAGTTCGCA


In [142]:
new_secondary_amplifiers = []
# regenerate new amplifier
for _i in range(6):
    _seq_str = amplifier_table['Secondary amplifier sequences'][_i]
    _seqs, _cts = np.unique(_seq_str.split(' '), return_counts=True)
    _lens = np.array([len(_seq) for _seq in _seqs], dtype=np.int)
    print(_lens)
    print(str(_seqs[np.where((_cts==5) * (_lens>10))[0]][-1]), 
          str(readout_sites[_i%3].seq) )
    # seq to replace
    _new_seq_str = str(_seq_str).replace(str(_seqs[np.where((_cts==5) * (_lens>10))[0]][-1]), 
                         str(readout_sites[_i%3].seq) ).replace(' ','')
    
    _new_seq = SeqRecord(Seq(_new_seq_str), id=f"{readout_sites[_i%3].id}rc_bit{amplifier_table['Bit'][_i]}_secondary", description='')
    new_secondary_amplifiers.append(_new_seq)
                         

[20  2 20  2]
ATGAGGAAAGTGGTGTGAGA TTTGCACTGCCGTCCTTGAC
[ 2 20 20]
GAGGAGTGGATAAATGGTGT GATCCGATTGGAACCGTCCC
[20 20  2]
AGTGTGGGATTGATGAGATA TGCGAACTGTCCGGCTTTCA
[20  2 20]
TGTGGTTTGGAGATGATAGA TTTGCACTGCCGTCCTTGAC
[20 20  2]
GAGATTAGAGATGAGTTGGA GATCCGATTGGAACCGTCCC
[20  2 20]
AGTTGAGGTGGGAGAGTATT TGCGAACTGTCCGGCTTTCA


In [136]:
_seqs[np.where((_cts==5) * (_lens>1))[0]]

array([], dtype='<U20')

In [106]:
len(new_primary_amplifiers[0])

130

In [143]:
readout_folder = r'\\10.245.74.212\Chromatin_NAS_2\Libraries\Readouts'
stv_readout_file = os.path.join(readout_folder, 'updated_Stvs.fasta')
ndb_readout_file = os.path.join(readout_folder, 'updated_NDBs.fasta')

kept_primary_amplifiers = library_tools.readouts.Screen_seqs_against_fasta(new_primary_amplifiers, 
                                                                           stv_readout_file)

kept_primary_amplifiers = library_tools.readouts.Screen_seqs_against_fasta(kept_primary_amplifiers, 
                                                                           ndb_readout_file)

- Screen sequences against given fasta file:\\10.245.74.212\Chromatin_NAS_2\Libraries\Readouts\updated_Stvs.fasta
-- 6 sequences loaded.
-- constructing reference table for fasta file
Mapping no. of seqs: 75
-- 6 sequences kept by allowing hits:0
- Screen sequences against given fasta file:\\10.245.74.212\Chromatin_NAS_2\Libraries\Readouts\updated_NDBs.fasta
-- 6 sequences loaded.
-- constructing reference table for fasta file
Mapping no. of seqs: 1283
-- 6 sequences kept by allowing hits:0


In [144]:
kept_secondary_amplifiers = library_tools.readouts.Screen_seqs_against_fasta(new_secondary_amplifiers, 
                                                                           stv_readout_file)

kept_secondary_amplifiers = library_tools.readouts.Screen_seqs_against_fasta(kept_secondary_amplifiers, 
                                                                           ndb_readout_file)

- Screen sequences against given fasta file:\\10.245.74.212\Chromatin_NAS_2\Libraries\Readouts\updated_Stvs.fasta
-- 6 sequences loaded.
-- constructing reference table for fasta file
Mapping no. of seqs: 75
-- 6 sequences kept by allowing hits:0
- Screen sequences against given fasta file:\\10.245.74.212\Chromatin_NAS_2\Libraries\Readouts\updated_NDBs.fasta
-- 6 sequences loaded.
-- constructing reference table for fasta file
Mapping no. of seqs: 1283
-- 6 sequences kept by allowing hits:0


In [147]:
print(new_primary_amplifiers[0].seq[:20].reverse_complement())

TAATGGGAAGGTGAAAGTGT


In [145]:
print(new_primary_amplifiers[0].seq)
print(new_secondary_amplifiers[0].seq)

ACACTTTCACCTTCCCATTATTACACTTTCACCTTCCCATTATTACACTTTCACCTTCCCATTATTACACTTTCACCTTCCCATTATTACACTTTCACCTTCCCATTATTGTCAAGGACGGCAGTGCAAA
TTTGCACTGCCGTCCTTGACTTTTTGCACTGCCGTCCTTGACTTTTTGCACTGCCGTCCTTGACTTTTTGCACTGCCGTCCTTGACTTTTTGCACTGCCGTCCTTGACTATAATGGGAAGGTGAAAGTGT


In [149]:
kept_secondary_amplifiers[0].id

'Stv_82rc_bit1_secondary'

In [148]:
print(kept_primary_amplifiers[0].seq)
print(kept_secondary_amplifiers[0].seq)

ACACTTTCACCTTCCCATTATTACACTTTCACCTTCCCATTATTACACTTTCACCTTCCCATTATTACACTTTCACCTTCCCATTATTACACTTTCACCTTCCCATTATTGTCAAGGACGGCAGTGCAAA
TTTGCACTGCCGTCCTTGACTTTTTGCACTGCCGTCCTTGACTTTTTGCACTGCCGTCCTTGACTTTTTGCACTGCCGTCCTTGACTTTTTGCACTGCCGTCCTTGACTATAATGGGAAGGTGAAAGTGT


In [124]:
print(readout_sites[0].reverse_complement().seq)
print(readout_sites[0].seq)

GTCAAGGACGGCAGTGCAAA
TTTGCACTGCCGTCCTTGAC


In [151]:
# generate csv file to order in IDT
import csv

with open(os.path.join(amplifier_folder, '20210201-_primary_amplifiers.csv'), 'w') as csvfile:
    csvwriter = csv.writer(csvfile, delimiter=',', lineterminator='\n',
                       quotechar='|', quoting=csv.QUOTE_MINIMAL)
    # write header
    _header = ['Name', 'Sequence', 'Scale', 'Purification']
    csvwriter.writerow(_header)
    # write sequence
    for _amplifier in kept_primary_amplifiers:
        _info = [_amplifier.id, str(_amplifier.seq), '100nm', 'STD']
        csvwriter.writerow(_info)

In [152]:
# generate csv file to order in IDT
import csv

with open(os.path.join(amplifier_folder, '20210201-_secondary_amplifiers.csv'), 'w') as csvfile:
    csvwriter = csv.writer(csvfile, delimiter=',', lineterminator='\n',
                       quotechar='|', quoting=csv.QUOTE_MINIMAL)
    # write header
    _header = ['Name', 'Sequence', 'Scale', 'Purification']
    csvwriter.writerow(_header)
    # write sequence
    for _amplifier in kept_secondary_amplifiers:
        _info = [_amplifier.id, str(_amplifier.seq), '100nm', 'STD']
        csvwriter.writerow(_info)

# load new readouts
readout_folder = r'\\10.245.74.212\Chromatin_NAS_2\Libraries\Readouts'
extended_stvs = []
with open(os.path.join(readout_folder, '20200121_extend_stv.fasta'), 'r') as _handle:
    for _readout in SeqIO.parse(_handle, "fasta"):
        extended_stvs.append(_readout)
print(extended_stvs)